### ISSUE TITLE
Package in `nixpkgs`

### ISSUE THREAD

**Issue by lovesegfault** [lilyball/nix-env.fish#12]
It'd be great if this was available under `nixpkgs#fishPlugins`, given the use-case.

**Comment by lilyball** [comment]
Interesting idea. I suppose that way you could install fish using `wrapFish` with the plugin, though I haven't looked at how that actually sets things up. Personally, I ended up switching to using something like

```nix
fish.override {
  fishEnvPreInit = source: source "${nix}/etc/profile.d/nix-daemon.sh";
}
```

which better replicates the NixOS initialization of fish, albeit with the downside that you have to compile fish now instead of getting it from the binary cache. And then when I adopted `nix-darwin` I just let it manage fish for me the way NixOS does.

All that to say, I don't actually use nix-env.fish myself anymore, nor am I in a position to test out alternative ways to install it. But the idea makes sense.

To that end, I would encourage you to submit a PR to nixpkgs. There's nothing to do in this repo (except for possibly updating the README if it gets added to nixpkgs), so I'm going to close this issue. Feel free to open a PR for a README change if it gets added to nixpkgs. Thank you for the suggestion!
