### ISSUE TITLE
I haver nix-env.fish install but `echo $NIX_PATH` returns empty line

### ISSUE THREAD

**Issue by phasmid42** [lilyball/nix-env.fish#13]
1. Installed `nix-env.fish` with `fisher install lilyball/nix-env.fish`
 2. Fresh installed nix ( [using Determinate Systems installer](https://github.com/DeterminateSystems/nix-installer?tab=readme-ov-file#determinate-nix-installer) ).
 3. Installed [nix-darwin](https://github.com/LnL7/nix-darwin?tab=readme-ov-file#step-1-creating-flakenix)
 4. After installing nix-darwin, the command`darwin-rebuild switch --flake ~/.config/nix-darwin` , returned error message: `fish: Unknown command: darwin-rebuild`
 5. `echo $NIX_PATH` returned empty line.
 
it is expected that $NIX_PATH is not empty.

**Comment by lilyball** [comment]
`$NIX_PATH` is not related to the existence of `darwin-rebuild`. With `nix-darwin`, you should only have a `$NIX_PATH` if you've provided a value for the `nix.nixPath` setting or `nix.channel.enable` is enabled (which it is by default, but perhaps you disabled it since the DetSys installer gives you a flakes-based setup?).

That said, if you're using `nix-darwin`, you don't need `nix-env.fish`. `nix-darwin` replicates the NixOS setup for fish (assuming you've set `programs.fish.enable`) so a nix-installed fish will configure itself. `nix-env.fish` is meant for integrating a non-Nix-installed fish with Nix (or for a Nix-installed fish on non-NixOS/`nix-darwin` if you don't want to override fish to customize its setup as that requires rebuilding it).

I'm going to go ahead and close this, and my recommendation to you is the following:

1. Uninstall `nix-env.fish`
2. Ensure `programs.fish.enable` is set in your `nix-darwin` setup.
3. If necessary, run an interactive or login bash shell in order to run `darwin-rebuild switch` since `programs.bash.enable` is set by default and so bash should have the right `$PATH`.
4. Once you've rebuilt with `programs.fish.enable`, then any subsequent interactive fish shells should be configured correctly and able to see `darwin-rebuild`.
